### ISSUE TITLE
allow direct set of model.Qprev = X in flux/thermal.pyx

### ISSUE THREAD

**Issue by steo85it** [sampotter/python-flux#20]
One difference leading to differences in #19 is the initialization method: in the F90 code, both Qprev and Qnp1 are given as input, while here only Qnp1. 
To initialize Qprev, I run model.step(0,Qprev), but this changes Tsurf at t_0. A more consistent way would be to allow for directly setting `model.Qprev = X` (which now gives an error).
I'm not sure if this issue really causes discrepancies in #19, but it's a difference...

**Comment by sampotter** [comment]
Ohh, yes OK, it makes sense to want to do this. Thanks for making the separate issue... easier to see the problem.

Try the latest commit https://github.com/sampotter/python-flux/commit/8cda72536f8fed7b1688687edfb66ff1d950af1c. I added a keyword argument to the constructor to make it so you can pass in an initial value for `Qprev`. Hope this helps.

The reason trying to set `model.Qprev = X` gives an error is because `Qprev` is a "property" right now. I figure it is probably a good idea to disallow the user from setting variables in the model willy nilly, so that the model doesn't accidentally get put into a meaningless state. Although setting `model.Qprev = X` in your case would have been totally fine... If you think it makes sense to make it easier to set the internal state of `PccThermalModel1D` let me know and I can fix it easily (basically just remove all those functions decorated with `@property` in thermal.pyx).

**Comment by steo85it** [comment]
Great, thanks! It works fine (even though I'd maybe call that parameter `Qinit` (?) to make it clearer. Unfortunately, it doesn't significantly change the outcome in terms of discrepancies.
Otherwise, I agree that allowing the user to change properties without any check wouldn't be a good practice: setters or function parameters like this are better. :)

**Comment by steo85it** [comment]
you were to quick, but I updated the test to go with your changes in PR #21
