### ISSUE TITLE
issue with new form_factors.py

### ISSUE THREAD

**Issue by steo85it** [sampotter/python-flux#56]
The issue seems to be with [this row](https://github.com/sampotter/python-flux/blob/80cc3644cfc3ff8bcf879928fd6d04729138ac0b/src/flux/form_factors.py#L49). If [this](https://github.com/sampotter/python-flux/blob/80cc3644cfc3ff8bcf879928fd6d04729138ac0b/src/flux/form_factors.py#L38) is changed to `indptr = [0]`, then the code doesn't crash, but it runs in what seems to be an infinite loop.

**Comment by sampotter** [comment]
Oops, thanks for catching that...

I pushed a change (c7381ccc87079d92c9aa2a9e22375f3eca57b37d) to do the equivalent of what you did but while keeping `indptr` as an `array` instead of changing it to a list.

This worked for me on pretty small test case. Trying on a little bit larger test now. (Using haworth.py to test for now.)

If the infinite loop behavior persists, let me know and we'll figure it out.

**Comment by steo85it** [comment]
It seems to work (and yes, my bad not spotting immediately how to solve it!), thanks! I'm relaunching the memory tests and let's see tomorrow morning.

**Comment by sampotter** [comment]
Thanks! No problem at all... I hadn't used this `array` class before either.
